# Generated by Django 3.0.3 on 2020-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200324_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_pic',
            field=models.ImageField(blank=True, default='jeez.png', null=True, upload_to=''),
        ),
    ]
