# Generated by Django 3.0.3 on 2020-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200417_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.png', null=True, upload_to=''),
        ),
    ]
