# Generated by Django 3.0.3 on 2020-05-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profile_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Profile'),
        ),
    ]
