# Generated by Django 3.0.6 on 2020-06-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200617_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='profile_pic',
        ),
    ]
